//HintName: DashboardView.g.cs
// <auto-generated/>
#nullable enable
namespace TestNamespace;

using System.Linq;
using Terminal.Gui;
using Terminal.Gui.ViewBase;
using Terminal.Gui.Stanza;

partial class DashboardView : Terminal.Gui.Stanza.IStanzaView<TestNamespace.DashboardViewModel>
{
    public DashboardView() : base()
    {
    }

    public DashboardView(TestNamespace.DashboardViewModel viewModel) : this()
    {
        this.ViewModel = viewModel;
    }

    private TestNamespace.DashboardViewModel? _viewModel;
    public TestNamespace.DashboardViewModel? ViewModel {
        get => _viewModel;
        set {
            if (object.ReferenceEquals(_viewModel, value)) return;

            _bindingContext.Dispose();
            _viewModel = value;
            _bindingContext = new BindingContext();

            if (value != null) InitializeComponent();
        }
    }

    private BindingContext _bindingContext = new();
    public BindingContext BindingContext => _bindingContext;

    protected void Bind<T>(System.Func<T> getter, System.Action<T> update, [System.Runtime.CompilerServices.CallerArgumentExpression(nameof(getter))] string expr = "")
    {
        if (this.ViewModel == null)
            throw new System.InvalidOperationException("ViewModel must be set before calling Bind.");
        BindingContext.AddBinding(this.ViewModel.Bind(expr, getter, update));
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _bindingContext.Dispose();
        }
        base.Dispose(disposing);
    }

    protected void InitializeComponent()
    {
        // 1. Instantiate controls
        FooterLabel ??= new();
        LeftPanel ??= new();
        RightPanel ??= new();

        // 2. Apply properties and layout
        RightPanel.X = Pos.Right(LeftPanel);
        FooterLabel.Y = Pos.AnchorEnd(1);
        FooterLabel.X = Pos.Center();
        FooterLabel.Width = Dim.Fill();

        // 3. Wire bindings

        // 4. Add to view hierarchy
        if (!this.SubViews.Contains(FooterLabel)) this.Add(FooterLabel);
        if (!this.SubViews.Contains(LeftPanel)) this.Add(LeftPanel);
        if (!this.SubViews.Contains(RightPanel)) this.Add(RightPanel);

        OnInitialized();
    }

    partial void OnInitialized();
}
