//HintName: MyView.g.cs
// <auto-generated/>
#nullable enable
namespace TestNamespace;

using Terminal.Gui;
using Terminal.Gui.ViewBase;
using Terminal.Gui.Stanza.Binding;

partial class MyView
{
    protected void InitializeComponent()
    {
        // 1. Instantiate controls
        MyLabel ??= new();

        // 2. Apply properties and layout
        MyLabel.Text = "Hello";

        // 3. Wire bindings

        // 4. Add to view hierarchy
        this.Add(MyLabel);
    }
}
