//HintName: MyView.g.cs
// <auto-generated/>
#nullable enable
namespace TestNamespace;

using Terminal.Gui;
using Terminal.Gui.ViewBase;
using Terminal.Gui.Stanza.Binding;

partial class MyView : Terminal.Gui.Stanza.Binding.IStanzaView<TestNamespace.MyViewModel>
{
    public MyView() : base()
    {
        this.Width = Dim.Auto();
        this.Height = Dim.Auto();
        this.CanFocus = true;
    }

    public MyView(TestNamespace.MyViewModel viewModel) : this()
    {
        this.ViewModel = viewModel;
    }

    private TestNamespace.MyViewModel? _viewModel;
    public TestNamespace.MyViewModel? ViewModel {
        get => field;
        set {
            field = value;
            if (value != null) InitializeComponent();
        }
    }

    private readonly BindingContext _bindingContext = new();
    public BindingContext BindingContext => _bindingContext;

    protected void Bind<T>(System.Func<T> getter, System.Action<T> update, [System.Runtime.CompilerServices.CallerArgumentExpression(nameof(getter))] string expr = "")
    {
        if (this.ViewModel == null)
            throw new System.InvalidOperationException("ViewModel must be set before calling Bind.");
        _bindingContext.AddBinding(this.ViewModel.Bind(expr, getter, update));
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _bindingContext.Dispose();
        }
        base.Dispose(disposing);
    }

    protected void InitializeComponent()
    {
        // 1. Instantiate controls
        MyLabel ??= new();

        // 2. Apply properties and layout
        MyLabel.Text = "Hello";

        // 3. Wire bindings

        // 4. Add to view hierarchy
        this.Add(MyLabel);
    }
}
