//HintName: DashboardView.g.cs
// <auto-generated/>
#nullable enable
namespace TestNamespace;

using Terminal.Gui;
using Terminal.Gui.ViewBase;
using Terminal.Gui.Stanza.Binding;

partial class DashboardView : Terminal.Gui.Stanza.Binding.IStanzaView<TestNamespace.DashboardViewModel>
{
    public DashboardView() : base()
    {
        this.Width = Dim.Auto();
        this.Height = Dim.Auto();
        this.CanFocus = true;
    }

    public DashboardView(TestNamespace.DashboardViewModel viewModel) : this()
    {
        this.ViewModel = viewModel;
    }

    private TestNamespace.DashboardViewModel? _viewModel;
    public TestNamespace.DashboardViewModel? ViewModel {
        get => field;
        set {
            field = value;
            if (value != null) InitializeComponent();
        }
    }

    private readonly BindingContext _bindingContext = new();
    public BindingContext BindingContext => _bindingContext;

    protected void Bind<T>(System.Func<T> getter, System.Action<T> update, [System.Runtime.CompilerServices.CallerArgumentExpression(nameof(getter))] string expr = "")
    {
        if (this.ViewModel == null)
            throw new System.InvalidOperationException("ViewModel must be set before calling Bind.");
        _bindingContext.AddBinding(this.ViewModel.Bind(expr, getter, update));
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _bindingContext.Dispose();
        }
        base.Dispose(disposing);
    }

    protected void InitializeComponent()
    {
        // 1. Instantiate controls
        FooterLabel ??= new();
        LeftPanel ??= new();
        RightPanel ??= new();

        // 2. Apply properties and layout
        RightPanel.X = Pos.Right(LeftPanel);
        FooterLabel.Y = Pos.AnchorEnd(1);
        FooterLabel.X = Pos.Center();
        FooterLabel.Width = Dim.Fill();

        // 3. Wire bindings

        // 4. Add to view hierarchy
        this.Add(FooterLabel);
        this.Add(LeftPanel);
        this.Add(RightPanel);
    }
}
