using System.Collections.Generic;
using System.Linq;
using System.Text;
using Terminal.Gui.Stanza.Abstractions.IR;
using Terminal.Gui.Stanza.Abstractions;

namespace Terminal.Gui.Stanza.Generators;

internal class InitializeComponentEmitter
{
    public string Emit(ViewDeclaration viewDecl, List<string> instantiationOrder)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"namespace {viewDecl.Namespace};");
        sb.AppendLine();
        sb.AppendLine("using Terminal.Gui;");
        sb.AppendLine("using Terminal.Gui.ViewBase;");
        sb.AppendLine("using Terminal.Gui.Stanza.Binding;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(viewDecl.ViewModelType))
        {
            sb.AppendLine($"partial class {viewDecl.ClassName} : Terminal.Gui.Stanza.BindableView<{viewDecl.ViewModelType}>");
        }
        else
        {
            sb.AppendLine($"partial class {viewDecl.ClassName}");
        }
        sb.AppendLine("{");
        sb.AppendLine("    protected override void InitializeComponent()");
        sb.AppendLine("    {");

        // 1. Instantiate views in dependency order
        sb.AppendLine("        // 1. Instantiate controls");
        foreach (var viewName in instantiationOrder)
        {
            sb.AppendLine($"        {viewName} ??= new();");
        }

        sb.AppendLine();

        // 2. Apply properties and layout
        sb.AppendLine("        // 2. Apply properties and layout");
        foreach (var assignment in viewDecl.PropertyAssignments)
        {
            if (assignment.IsLayoutConstraint) continue;

            var propName = assignment.PropertyName switch
            {
                "PositionX" => "X",
                "PositionY" => "Y",
                _ => assignment.PropertyName
            };
            
            sb.AppendLine($"        {assignment.OwnerView}.{propName} = {assignment.ValueExpression};");
        }

        foreach (var constraint in viewDecl.LayoutConstraints)
        {
            var posMethod = constraint.ConstraintType == "Bottom" ? "Bottom" : "Right";
            sb.AppendLine($"        {constraint.SourceView}.{constraint.TargetProperty} = Pos.{posMethod}({constraint.ReferencedView});");
        }

        sb.AppendLine();

        // 3. Wire bindings
        sb.AppendLine("        // 3. Wire bindings");
        foreach (var binding in viewDecl.Bindings)
        {
            // Map synthetic property names to extension methods
            var bindMethod = binding.PropertyName switch
            {
                "BindText" => "ApplyBindText",
                "BindChecked" => "ApplyBindChecked",
                "BindValue" => "ApplyBindValue",
                "BindCommand" => "ApplyBindCommand",
                "BindVisible" => "ApplyBindVisible",
                "BindEnabled" => "ApplyBindEnabled",
                _ => "ApplyBind" // Fallback
            };

            if (bindMethod == "ApplyBindCommand")
            {
                sb.AppendLine($"        BindingContext.AddBinding({binding.OwnerView}.{bindMethod}(this.ViewModel!, this.ViewModel!.{binding.ViewModelProperty}));");
            }
            else if ((bindMethod == "ApplyBindText" || bindMethod == "ApplyBindChecked") && binding.BindingMode == BindingMode.TwoWay)
            {
                sb.AppendLine($"        BindingContext.AddBinding({binding.OwnerView}.{bindMethod}(this.ViewModel!, \"{binding.ViewModelProperty}\", vm => vm.{binding.ViewModelProperty}, (vm, val) => vm.{binding.ViewModelProperty} = val));");
            }
            else
            {
                sb.AppendLine($"        BindingContext.AddBinding({binding.OwnerView}.{bindMethod}(this.ViewModel!, \"{binding.ViewModelProperty}\", vm => vm.{binding.ViewModelProperty}));");
            }
        }

        sb.AppendLine();
        sb.AppendLine("        // 4. Add to view hierarchy");
        foreach (var viewName in instantiationOrder)
        {
            sb.AppendLine($"        this.Add({viewName});");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
