//HintName: GlobalView.g.cs
// <auto-generated/>
#nullable enable

using Stanza.TerminalGui;

partial class GlobalView : IStanzaView<GlobalViewModel>
{
    private BindingContext _bindingContext = new();
    public BindingContext BindingContext => _bindingContext;
    private GlobalViewModel? _viewModel;

    public GlobalViewModel? ViewModel
    {
        get => _viewModel;
        set
        {
            if (object.ReferenceEquals(_viewModel, value)) return;
            _viewModel = value;
            ApplyBindings();
        }
    }

    partial void OnApplyBindings(BindingContext context);
    private void ApplyBindings()
    {
        _bindingContext.Dispose();
        _bindingContext = new BindingContext();
        if (_viewModel == null) return;

        _bindingContext.AddBinding(StatusLabel.ApplyBindText(_viewModel, "Status", x => x.Status, (x, val) => x.Status = val));
        OnApplyBindings(_bindingContext);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing) _bindingContext.Dispose();
        base.Dispose(disposing);
    }
}