//HintName: StanzaLoggingExtensions.g.cs
// <auto-generated/>
#nullable enable

namespace Stanza.TerminalGui;

internal sealed class MelLoggerAdapter : global::Stanza.TerminalGui.ILogger
{
    private readonly global::Microsoft.Extensions.Logging.ILoggerFactory _factory;

    internal MelLoggerAdapter(global::Microsoft.Extensions.Logging.ILoggerFactory factory)
    {
        _factory = factory;
    }

    public void Log(global::Stanza.TerminalGui.LogLevel level, string message, string category)
    {
        var logger = _factory.CreateLogger(category);
        var melLevel = level switch
        {
            global::Stanza.TerminalGui.LogLevel.Debug => global::Microsoft.Extensions.Logging.LogLevel.Debug,
            global::Stanza.TerminalGui.LogLevel.Info => global::Microsoft.Extensions.Logging.LogLevel.Information,
            global::Stanza.TerminalGui.LogLevel.Warn => global::Microsoft.Extensions.Logging.LogLevel.Warning,
            global::Stanza.TerminalGui.LogLevel.Error => global::Microsoft.Extensions.Logging.LogLevel.Error,
            _ => global::Microsoft.Extensions.Logging.LogLevel.Information
        };
        
        global::Microsoft.Extensions.Logging.LoggerExtensions.Log(logger, melLevel, message);
    }

    public void LogError(global::System.Exception exception, string message, string category)
    {
        var logger = _factory.CreateLogger(category);
        global::Microsoft.Extensions.Logging.LoggerExtensions.LogError(logger, exception, message);
    }
}
public static class StanzaLoggingExtensions
{
    /// <summary>
    /// Wires Stanza's internal logging into the application's MEL pipeline.
    /// Call this after the service provider is built so that <see cref="Microsoft.Extensions.Logging.ILoggerFactory"/> is available.
    /// </summary>
    public static System.IServiceProvider UseStanzaLogging(this System.IServiceProvider provider)
    {
        StanzaConfig.Logger = new MelLoggerAdapter(
            (Microsoft.Extensions.Logging.ILoggerFactory)provider.GetService(typeof(Microsoft.Extensions.Logging.ILoggerFactory))!
        );
        return provider;
    }
}
