//HintName: MyView.g.cs
// <auto-generated/>
#nullable enable
namespace TestNamespace;

using Stanza.TerminalGui;

partial class MyView : IStanzaView<TestNamespace.MyViewModel>
{
    private BindingContext _bindingContext = new();
    public BindingContext BindingContext => _bindingContext;
    private TestNamespace.MyViewModel? _viewModel;

    public TestNamespace.MyViewModel? ViewModel
    {
        get => _viewModel;
        set
        {
            if (object.ReferenceEquals(_viewModel, value)) return;
            _viewModel = value;
            ApplyBindings();
        }
    }

    partial void OnApplyBindings(BindingContext context);
    private void ApplyBindings()
    {
        _bindingContext.Dispose();
        _bindingContext = new BindingContext();
        if (_viewModel == null) return;

        _bindingContext.AddBinding(SaveButton.ApplyBindCommand(_viewModel.SaveCommand));
        OnApplyBindings(_bindingContext);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing) _bindingContext.Dispose();
        base.Dispose(disposing);
    }
}