//HintName: MyView.g.cs
// <auto-generated/>
#nullable enable
namespace TestNamespace;

using Stanza.TerminalGui;

partial class MyView : IStanzaView<TestNamespace.MyViewModel>
{
    private BindingContext _bindingContext = new();
    public BindingContext BindingContext => _bindingContext;
    private TestNamespace.MyViewModel? _viewModel;

    public TestNamespace.MyViewModel? ViewModel
    {
        get => _viewModel;
        set
        {
            if (object.ReferenceEquals(_viewModel, value)) return;
            StanzaConfig.Trace($"[Lifecycle] ViewModel changed on MyView", LogLevel.Debug);
            _viewModel = value;
            StanzaConfig.Trace($"[Lifecycle] ViewModel attached to MyView", LogLevel.Info); 
            ApplyBindings();
        }
    }

    partial void OnApplyBindings(BindingContext context);
    private void ApplyBindings()
    {
        StanzaConfig.Trace("[Lifecycle] Disposing old bindings for MyView", LogLevel.Debug);
        _bindingContext.Dispose();
        _bindingContext = new BindingContext();
        if (_viewModel == null)
        {
            StanzaConfig.Trace("[Lifecycle] ViewModel is null for MyView, skipping bindings.", LogLevel.Debug);
            return;
        }
        StanzaConfig.Trace("[Lifecycle] Applying 1 bindings for MyView...", LogLevel.Debug);

        StanzaConfig.Trace("[Binding] Wiring SaveButton (BindCommand) -> ViewModel.SaveCommand (Mode: OneWay)", LogLevel.Debug);
        _bindingContext.AddBinding(SaveButton.ApplyBindCommand(_viewModel.SaveCommand));
        StanzaConfig.Trace("[Lifecycle] Bindings applied successfully for MyView.", LogLevel.Debug);
        OnApplyBindings(_bindingContext);
    }

    protected override void Dispose(bool disposing)
    {
        StanzaConfig.Trace($"[Lifecycle] Disposing MyView (disposing: {disposing})", LogLevel.Debug);
        if (disposing) _bindingContext.Dispose();
        base.Dispose(disposing);
    }
}