using System.Text;

namespace Stanza.TerminalGui.Generators;

public static class Emitter
{
    public static string Emit(ViewIR view)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (view.Namespace != "Global")
        {
            sb.AppendLine($"namespace {view.Namespace};");
        }
        sb.AppendLine();
        sb.AppendLine("using Stanza.TerminalGui;");
        sb.AppendLine();

        // Class Declaration
        sb.AppendLine($"partial class {view.ClassName} : IStanzaView<{view.ViewModelType}>");
        sb.AppendLine("{");

        // Plumbing (Static block)
        sb.Append(
            $$"""
    private BindingContext _bindingContext = new();
    public BindingContext BindingContext => _bindingContext;
    private {{view.ViewModelType}}? _viewModel;

    public {{view.ViewModelType}}? ViewModel
    {
        get => _viewModel;
        set
        {
            if (object.ReferenceEquals(_viewModel, value)) return;
            _viewModel = value;
            ApplyBindings();
        }
    }

    partial void OnApplyBindings(BindingContext context);

"""
        );

        // Binding Method Start
        sb.AppendLine("    private void ApplyBindings()");
        sb.AppendLine("    {");
        sb.AppendLine("        _bindingContext.Dispose();");
        sb.AppendLine("        _bindingContext = new BindingContext();");
        sb.AppendLine("        if (_viewModel == null) return;");
        sb.AppendLine();

        // The Dynamic Loop (AppendLines are great here)
        foreach (var binding in view.Bindings)
        {
            var target = binding.ControlName;
            var vmProp = binding.ViewModelPropertyName;
            var setter = binding.Mode == "TwoWay" ? $", (x, val) => x.{vmProp} = val" : "";

            string method = binding.BindingType switch
            {
                "BindText" => "ApplyBindText",
                "BindChecked" => "ApplyBindChecked",
                "BindVisible" => "ApplyBindVisible",
                "BindEnabled" => "ApplyBindEnabled",
                "BindCommand" => "ApplyBindCommand",
                _ => throw new NotImplementedException(),
            };

            if (method != null)
            {
                // Command is special (doesn't take the lambda/propertyName args)
                if (binding.BindingType == "BindCommand")
                    sb.AppendLine(
                        $"        _bindingContext.AddBinding({target}.{method}(_viewModel.{vmProp}));"
                    );
                else
                    sb.AppendLine(
                        $"        _bindingContext.AddBinding({target}.{method}(_viewModel, \"{vmProp}\", x => x.{vmProp}{setter}));"
                    );
            }
        }

        // Method End & Dispose
        sb.Append(
            """

        OnApplyBindings(_bindingContext);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing) _bindingContext.Dispose();
        base.Dispose(disposing);
    }
}
"""
        );

        return sb.ToString();
    }
}
