using System.Text;

namespace Stanza.TerminalGui.Generators; // Add this!

public static class Emitter
{
    public static string Emit(ViewIR view)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");

        if (view.Namespace != "Global")
        {
            sb.AppendLine($"namespace {view.Namespace};");
        }
        sb.AppendLine();
        sb.AppendLine("using Stanza.TerminalGui;");
        sb.AppendLine();
        sb.AppendLine($"partial class {view.ClassName} : IStanzaView<{view.ViewModelType}>");
        sb.AppendLine("{");

        // MVVM Plumbing
        sb.AppendLine("    private BindingContext _bindingContext = new();");
        sb.AppendLine("    public BindingContext BindingContext => _bindingContext;");
        sb.AppendLine($"    private {view.ViewModelType}? _viewModel;");
        sb.AppendLine();
        sb.AppendLine($"    public {view.ViewModelType}? ViewModel");
        sb.AppendLine("    {");
        sb.AppendLine("        get => _viewModel;");
        sb.AppendLine("        set");
        sb.AppendLine("        {");
        sb.AppendLine("            if (object.ReferenceEquals(_viewModel, value)) return;");
        sb.AppendLine("            _viewModel = value;");
        sb.AppendLine("            ApplyBindings();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Binding Logic
        sb.AppendLine("    private void ApplyBindings()");
        sb.AppendLine("    {");
        sb.AppendLine("        _bindingContext.Dispose();");
        sb.AppendLine("        _bindingContext = new BindingContext();");
        sb.AppendLine("        if (_viewModel == null) return;");
        sb.AppendLine();

        // Inside Emitter.Emit(), update the switch statement:

        foreach (var binding in view.Bindings)
        {
            var target = binding.ControlName;
            var vmProp = binding.ViewModelPropertyName;

            // Conditionally generate the setter based on the Mode
            var setterArg = binding.Mode == "TwoWay" ? $", (x, val) => x.{vmProp} = val" : ""; // Empty for OneWay

            switch (binding.BindingType)
            {
                case "BindText":
                    sb.AppendLine(
                        $"        _bindingContext.AddBinding({target}.ApplyBindText(_viewModel, \"{vmProp}\", x => x.{vmProp}{setterArg}));"
                    );
                    break;
                case "BindChecked":
                    sb.AppendLine(
                        $"        _bindingContext.AddBinding({target}.ApplyBindChecked(_viewModel, \"{vmProp}\", x => x.{vmProp}{setterArg}));"
                    );
                    break;
                case "BindVisible":
                    sb.AppendLine(
                        $"        _bindingContext.AddBinding({target}.ApplyBindVisible(_viewModel, \"{vmProp}\", x => x.{vmProp}));"
                    );
                    break;
                case "BindEnabled":
                    sb.AppendLine(
                        $"        _bindingContext.AddBinding({target}.ApplyBindEnabled(_viewModel, \"{vmProp}\", x => x.{vmProp}));"
                    );
                    break;
                case "BindCommand":
                    sb.AppendLine(
                        $"        _bindingContext.AddBinding({target}.ApplyBindCommand(_viewModel, _viewModel.{vmProp}));"
                    );
                    break;
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // Cleanup
        sb.AppendLine("    protected override void Dispose(bool disposing)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (disposing) _bindingContext.Dispose();");
        sb.AppendLine("        base.Dispose(disposing);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
