using System.Collections.Generic;
using System.Linq;
using System.Text;
using Terminal.Gui.Stanza;
using Terminal.Gui.Stanza.IR;

namespace Terminal.Gui.Stanza.Generators;

internal class InitializeComponentEmitter
{
    public string Emit(ViewDeclaration viewDecl, List<string> instantiationOrder)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {viewDecl.Namespace};");
        sb.AppendLine();
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using Terminal.Gui;");
        sb.AppendLine("using Terminal.Gui.ViewBase;");
        sb.AppendLine("using Terminal.Gui.Stanza;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(viewDecl.ViewModelType))
        {
            sb.AppendLine(
                $"partial class {viewDecl.ClassName} : Terminal.Gui.Stanza.IStanzaView<{viewDecl.ViewModelType}>"
            );
            sb.AppendLine("{");
            if (viewDecl.GenerateParameterlessConstructor)
            {
                sb.AppendLine($"    public {viewDecl.ClassName}() : base()");
                sb.AppendLine("    {");
                if (!string.IsNullOrEmpty(viewDecl.Title))
                    sb.AppendLine($"        this.Title = \"{viewDecl.Title}\";");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            if (viewDecl.GenerateViewModelConstructor)
            {
                sb.AppendLine(
                    $"    public {viewDecl.ClassName}({viewDecl.ViewModelType} viewModel) : this()"
                );
                sb.AppendLine("    {");
                sb.AppendLine("        this.ViewModel = viewModel;");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine($"    private {viewDecl.ViewModelType}? _viewModel;");
            sb.AppendLine($"    public {viewDecl.ViewModelType}? ViewModel {{");
            sb.AppendLine("        get => _viewModel;");
            sb.AppendLine("        set {");
            sb.AppendLine("            if (object.ReferenceEquals(_viewModel, value)) return;");
            sb.AppendLine();
            sb.AppendLine("            _bindingContext.Dispose();");
            sb.AppendLine("            _viewModel = value;");
            sb.AppendLine("            _bindingContext = new BindingContext();");
            sb.AppendLine();
            sb.AppendLine("            if (value != null) InitializeComponent();");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private BindingContext _bindingContext = new();");
            sb.AppendLine("    public BindingContext BindingContext => _bindingContext;");
            sb.AppendLine();
            sb.AppendLine(
                "    protected void Bind<T>(System.Func<T> getter, System.Action<T> update, [System.Runtime.CompilerServices.CallerArgumentExpression(nameof(getter))] string expr = \"\")"
            );
            sb.AppendLine("    {");
            sb.AppendLine("        if (this.ViewModel == null)");
            sb.AppendLine(
                "            throw new System.InvalidOperationException(\"ViewModel must be set before calling Bind.\");"
            );
            sb.AppendLine(
                "        BindingContext.AddBinding(this.ViewModel.Bind(expr, getter, update));"
            );
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    protected override void Dispose(bool disposing)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (disposing)");
            sb.AppendLine("        {");
            sb.AppendLine("            _bindingContext.Dispose();");
            sb.AppendLine("        }");
            sb.AppendLine("        base.Dispose(disposing);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine($"partial class {viewDecl.ClassName}");
            sb.AppendLine("{");
        }
        sb.AppendLine("    protected void InitializeComponent()");
        sb.AppendLine("    {");

        // 1. Instantiate views in dependency order
        sb.AppendLine("        // 1. Instantiate controls");
        foreach (var viewName in instantiationOrder)
        {
            sb.AppendLine($"        {viewName} ??= new();");
            if (
                viewDecl.SubviewsWithViewModel != null
                && viewDecl.SubviewsWithViewModel.Contains(viewName)
            )
            {
                sb.AppendLine($"        {viewName}.ViewModel = this.ViewModel;");
            }
        }

        sb.AppendLine();

        // 2. Apply properties and layout
        sb.AppendLine("        // 2. Apply properties and layout");
        foreach (var assignment in viewDecl.PropertyAssignments)
        {
            var propName = assignment.PropertyName switch
            {
                "PositionX" => "X",
                "PositionY" => "Y",
                _ => assignment.PropertyName,
            };

            sb.AppendLine(
                $"        {assignment.OwnerView}.{propName} = {assignment.ValueExpression};"
            );
        }

        sb.AppendLine();

        // 3. Wire bindings
        sb.AppendLine("        // 3. Wire bindings");
        foreach (var binding in viewDecl.Bindings)
        {
            // Map synthetic property names to extension methods
            var bindMethod = binding.PropertyName switch
            {
                "BindText" => "ApplyBindText",
                "BindChecked" => "ApplyBindChecked",
                "BindValue" => "ApplyBindValue",
                "BindCommand" => "ApplyBindCommand",
                "BindVisible" => "ApplyBindVisible",
                "BindEnabled" => "ApplyBindEnabled",
                _ => "ApplyBind", // Fallback
            };

            if (bindMethod == "ApplyBindCommand")
            {
                sb.AppendLine(
                    $"        BindingContext.AddBinding({binding.OwnerView}.{bindMethod}(this.ViewModel!, this.ViewModel!.{binding.ViewModelProperty}));"
                );
            }
            else if (
                (bindMethod == "ApplyBindText" || bindMethod == "ApplyBindChecked")
                && binding.BindingMode == BindingMode.TwoWay
            )
            {
                sb.AppendLine(
                    $"        BindingContext.AddBinding({binding.OwnerView}.{bindMethod}(this.ViewModel!, \"{binding.ViewModelProperty}\", vm => vm.{binding.ViewModelProperty}, (vm, val) => vm.{binding.ViewModelProperty} = val));"
                );
            }
            else
            {
                var getterExpr = binding.RequiresToString
                    ? $"vm => vm.{binding.ViewModelProperty}.ToString()"
                    : $"vm => vm.{binding.ViewModelProperty}";
                sb.AppendLine(
                    $"        BindingContext.AddBinding({binding.OwnerView}.{bindMethod}(this.ViewModel!, \"{binding.ViewModelProperty}\", {getterExpr}));"
                );
            }
        }

        sb.AppendLine();
        sb.AppendLine("        // 4. Add to view hierarchy");
        foreach (var viewName in instantiationOrder)
        {
            sb.AppendLine(
                $"        if (!this.SubViews.Contains({viewName})) this.Add({viewName});"
            );
        }

        sb.AppendLine();
        sb.AppendLine("        OnInitialized();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    partial void OnInitialized();");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
