namespace Terminal.Gui.Stanza;

using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Stanza.Binding;
using Terminal.Gui.ViewBase;


/// <summary>
/// Base class for declarative Stanza views. Provides binding context and enforces generated code pattern.
/// </summary>
public abstract class BindableView<TViewModel> : View
    where TViewModel : INotifyPropertyChanged
{
    protected BindingContext BindingContext { get; private set; } = new();

    private TViewModel? _viewModel;
    public TViewModel? ViewModel 
    { 
        get => _viewModel;
        set
        {
            _viewModel = value;
            if (_viewModel != null)
            {
                InitializeComponent();
            }
        }
    }

    /// <summary>
    /// Called during initialization to wire up properties, layout, and bindings.
    /// This method is generated by TuiViewGenerator and should not be overridden.
    /// </summary>
    protected abstract void InitializeComponent();

    public BindableView()
    {
        Width = Dim.Fill();
        Height = Dim.Fill();
        CanFocus = true;
    }

    /// <summary>
    /// Initializes a new instance with a pre-configured ViewModel (Constructor Injection).
    /// </summary>
    public BindableView(TViewModel viewModel) : this()
    {
        ViewModel = viewModel;
    }

    /// <summary>
    /// Helper method to create custom one-way bindings from ViewModel properties to the UI.
    /// </summary>
    protected void Bind<T>(
        Func<T> getter,
        Action<T> updateUi,
        [System.Runtime.CompilerServices.CallerArgumentExpression(nameof(getter))] string expression = default!
    )
    {
        if (ViewModel == null)
            throw new InvalidOperationException("ViewModel must be set before calling Bind.");

        BindingContext.AddBinding(ViewModel.Bind(getter, updateUi, expression));
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            BindingContext?.Dispose();
        }
        base.Dispose(disposing);
    }
}
